#167826411 Add book a seat number functionality.
nziokaivy/Wayfarer_project pull request #45
Opened 2019-08-12 09:16 UTC by nziokaivy

#### What does this PR do?
Adds a book seat number functionality

#### Description of Task to be completed?
- Add HTML script to the book seat page.
- Add styling to the book seat HTML file. 

#### How should this be manually tested?
Clone this repository and run `npm install && run test`

#### Any background context you want to provide?
Adding a book seat number functionality allows users to book which seat they prefer among the not booked seats.

#### What are the relevant pivotal tracker stories?
#167826411

#### Screenshots (if appropriate)
![Screenshot from 2019-08-12 12-15-24](https://user-images.githubusercontent.com/45204494/62855443-eddc6280-bcfa-11e9-9861-55f5fe68e01b.png)

2019-08-12 10:38 UTC, oesukam requested changes
Great job. You just have to add blank lines at the of you files and remove unnecessary spaces from your HTML files.

2019-08-12 10:38 UTC, oesukam commented on UI/html/specifictrip.html
>  </html>
@nziokaivy Blank line required

2019-08-12 10:38 UTC, oesukam commented on UI/js/index.js
>    }
@nziokaivy Blank line required

2019-08-13 03:08 UTC, nziokaivy commented
> Great job. You just have to add blank lines at the of you files and remove unnecessary spaces from your HTML files.

@oesukam I have now removed all the unwanted spaces and add blank lines at the end of files

2019-08-13 05:54 UTC, oesukam commented
@nziokaivy You have merge conflict under your `package.json` file that you forgot to resolve

2019-08-13 09:14 UTC, oesukam approved these changes

2019-08-13 10:27 UTC, merged